### ISSUE TITLE
IE volume

### ISSUE THREAD

**Issue by randyL78** [randyL78/Interactive-Video-Player#1]
### TODO
* [ ] Create basic slider button that is browser independent
* [ ] Ensure that slider button is accessible
* [ ] Add custom properties to slider to display vertical or horizontal
* [ ] Add hooks to be able to customize for current project or via css
* [ ] Incorporate new slider into volume control and color picker
* [x] Drink coffee throughout ☕️
