### ISSUE TITLE
Make more plugin worthy

### ISSUE THREAD

**Issue by randyL78** [randyL78/Interactive-Video-Player#3]
## TODO

* [ ] Reformat player skin as an object
* [ ] Add properties that can be modified on the fly for external users
* [ ] Remove project specific code and place in separate .js file
